apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chapeaux-porteur
  labels:
    sandbox: serverless
    sandbox-serverless: porteur

spec:
  template:
    spec:
      containers:
        - image: quay.io/ldary/kn-backend:latest